/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 BUSs.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BUSs(props) {
  const { nodes, materials } = useGLTF('/BUSs.glb')
  return (
    <group {...props} dispose={null} scale={25}>
      <mesh geometry={nodes.BackWheels.geometry} material={materials.Atlas} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.FrontWheel_L.geometry} material={materials.Atlas} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.FrontWheel_R.geometry} material={materials.Atlas} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Truck_1.geometry} material={materials.Atlas} />
        <mesh geometry={nodes.Truck_2.geometry} material={materials.Headlights} />
        <mesh geometry={nodes.Truck_3.geometry} material={materials.BrakeLight} />
        <mesh geometry={nodes.Truck_4.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/BUSs.glb')
