/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Moto.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Moto(props) {
  const { nodes, materials } = useGLTF('/Moto.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh399081721.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh399081721_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh861611824.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh861611824_1.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh861611824_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh861611824_3.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh861611824_4.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh861611824_5.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh861611824_6.geometry} material={materials.mat0} />
      <mesh geometry={nodes.mesh861611824_7.geometry} material={materials.mat2} />
      <mesh geometry={nodes.mesh861611824_8.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh861611824_9.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh861611824_10.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh861611824_11.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh861611824_12.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh861611824_13.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh861611824_14.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh861611824_15.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh861611824_16.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh861611824_17.geometry} material={materials.mat3} />
    </group>
  )
}

useGLTF.preload('/Moto.glb')
