/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Taxi.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Taxi(props) {
  const { nodes, materials } = useGLTF('/Taxi.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Taxi_Cube009-Mesh'].geometry} material={materials.Yellow} />
      <mesh geometry={nodes['Taxi_Cube009-Mesh_1'].geometry} material={materials.Windows} />
      <mesh geometry={nodes['Taxi_Cube009-Mesh_2'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Taxi_Cube009-Mesh_3'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Taxi_Cube009-Mesh_4'].geometry} material={materials.Headlights} />
      <mesh geometry={nodes['Taxi_Cube009-Mesh_5'].geometry} material={materials.TailLights} />
      <mesh geometry={nodes['Taxi_BackWheels_Cube010-Mesh'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Taxi_BackWheels_Cube010-Mesh_1'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Taxi_FrontLeftWheel_Cube013-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Taxi_FrontLeftWheel_Cube013-Mesh_1'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Taxi_FrontRightWheel_Cube014-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Taxi_FrontRightWheel_Cube014-Mesh_1'].geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('/Taxi.glb')
